name: CI with Kaniko and GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image with Kaniko
        env:
          DOCKER_REGISTRY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx build \
            --progress plain \
            --builder kaniko \
            --platform linux/amd64 \
            --file path/to/Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/my-image:${{ github.sha }} \
            --push .
